//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by Atom templates.
//

import Foundation
import Atom

extension ___VARIABLE_baseClass:identifier___: AtomSubscriber
{
    typealias EventType = ___VARIABLE_eventEnumName:identifier___
    
    func stateChanged(event: EventType)
    {
        switch event {
        default:
            ()
        }
    }
}