//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by Atom templates.
//

import Foundation
import Atom

struct ___FILEBASENAMEASIDENTIFIER___: AtomState {

    typealias EventType = ___VARIABLE_eventEnumName:identifier___
    
    static var parentClass: AtomNode.Type = <#PARENT_CLASS_TYPE#>.self
    
    static func react(optionalCurrent: ___FILEBASENAMEASIDENTIFIER___?, event: EventType) -> ___FILEBASENAMEASIDENTIFIER___ {
        guard var current = optionalCurrent else { return initial() }
        
        switch event {
        /// cases here
        default:
            break
        }
        
        return current
    }
    
    static func initial() -> ___FILEBASENAMEASIDENTIFIER___ {
        return ___FILEBASENAMEASIDENTIFIER___()
    }
}